### ISSUE TITLE
How to setup environment for build LXC image

### ISSUE THREAD

**Issue by helloworlde** [Chiogros/image-mageia#1]
Hi, I'm new to LXC/LXD, I want to build a LXC image by using distrobuilder,  then I found this useful project, the action yaml is `runs-on: self-hosted` in [build-lxc-image.yaml](https://github.com/helloworlde/image-mageia/blob/1787b947343cb17103b0b05a6bc7362624e83684/.github/workflows/build-lxc-image.yaml#L17), I need run build image by GitHub Action, but I don't know how to setup dependencies step, could you please tell me how should I do that? Thank you very much.

**Comment by Chiogros** [comment]
Hi,
Steps are executed in order, you don't have to manage it.
However, you can manage jobs execution with the `needs` instruction.

**Comment by helloworlde** [comment]
Thanks.
